name: First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: "Print Today's Date"
        run: date

      - name: "Say Hi"
        run: echo "Your name is ${{ github.actor }}"