name: First Workflow

on: [push]  # <-- trigger

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "👋 Hello, ${{ github.actor }}! Welcome to GitHub Actions!"
